FROM node:24-bookworm-slim

# Define the version of Watchman to install
ARG WATCHMAN_VERSION=v2026.04.06.00

# Install dependencies
RUN apt-get update && apt-get install -y \
  curl \
  wget \
  unzip \
  libssl-dev \
  ca-certificates \
  && rm -rf /var/lib/apt/lists/*

# Download and install Watchman
RUN wget https://github.com/facebook/watchman/releases/download/${WATCHMAN_VERSION}/watchman-${WATCHMAN_VERSION}-linux.zip \
  && unzip watchman-${WATCHMAN_VERSION}-linux.zip \
  && cd watchman-${WATCHMAN_VERSION}-linux \
  && mkdir -p /usr/local/bin /usr/local/lib /usr/local/var/run/watchman \
  && cp bin/* /usr/local/bin/ \
  && cp lib/* /usr/local/lib/ \
  && chmod 755 /usr/local/bin/watchman \
  && chmod 2777 /usr/local/var/run/watchman \
  && cd .. \
  && rm -rf watchman-${WATCHMAN_VERSION}-linux*

# Set workdir
WORKDIR /app

# Copy and install dependencies
COPY package.json yarn.lock ./
RUN yarn install

# Copy app files
COPY . .

RUN chmod +x ./docker-dev-entrypoint
ENTRYPOINT ["./docker-dev-entrypoint"]

# Expose Vite dev server
EXPOSE 5173
CMD ["yarn", "dev"]
